### ISSUE TITLE
iOS Build - boldTextOverride

### ISSUE THREAD

**Issue by Simonpiro** [AmirJabbari/flutter-glow#7]
Hello team,
I am using your great widget in my app and recently i have encountered this issue when building app for iOS:
`Error (Xcode): ../.pub-cache/hosted/pub.dev/flutter_glow-0.3.0/lib/src/widget/glow_text.dart:79:20: Error: Member not found: 'MediaQuery.boldTextOverride'.`
Did apple changed something which requires some update in your widget? 
Thank you and have a great day !
Simon

**Comment by payam-zahedi** [comment]
Thanks for creating this Issue and PR 

Have you tested it?

is it working currectly?

**Comment by Simonpiro** [comment]
Hello Payam,
No i wasn't able to test it. Do you have some testing framework?
Simon

________________________________

**Comment by IvanGast** [comment]
I have also this issue on Android after upgrading flutter to the latest version.

**Comment by ChunhThanhDe** [comment]
Here is the issue and its solution converted to English and formatted in Markdown:

---

### Issue Description

The following error occurs when trying to compile the application:

```
../../AppData/Local/Pub/Cache/hosted/pub.dev/flutter_glow-0.3.0/lib/src/widget/glow_text.dart:79:20: Error: Member not found: 'MediaQuery.boldTextOverride'.
    if (MediaQuery.boldTextOverride(context)) {
                   ^^^^^^^^^^^^^^^^
Failed to compile application.
```

### Solution

To fix this issue, replace `MediaQuery.boldTextOverride` with `MediaQuery.boldTextOf`.

#### Original Code:
```dart
if (MediaQuery.boldTextOverride(context)) {
```

#### Updated Code:
```dart
if (MediaQuery.boldTextOf(context)) {
```

I have verified this patch #8 , and I confirm that it is valid. Please integrate this patch. @AmirJabbari 

---

**Comment by AmirJabbari** [comment]
Hi everyone,

Thank you for your feedback and patience. I'm happy to inform you that this issue has been resolved. You can now use the updated version of the widget without any problems.

Thanks again for your support, and have a great day!

Best regards,
